Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -60,11 +60,14 @@ jobs:
 
     - name: Check SonarQube Quality Gate status
       run: |
-        RESULT=$(curl -s -u ${{ secrets.SONAR_TOKEN }} "http://4.247.31.109:9000//api/qualitygates/project_status?projectKey=Petclinic" | jq -r '.projectStatus.status')
+        response=$(curl -s -u ${{ secrets.SONAR_TOKEN }} "http://4.247.31.109:9000/api/qualitygates/project_status?projectKey=Petclinic")
+        echo "API Response: $response"
+        RESULT=$(echo $response | jq -r '.projectStatus.status')
         echo "Quality Gate status: $RESULT"
         if [ "$RESULT" != "OK" ]; then
-          echo "Quality Gate failed!"
-          exit 1
+        echo "Quality Gate failed!"
+        exit 1
         else
-          echo "Quality Gate passed!"
-          fi
+        echo "Quality Gate passed!"
+        fi
+
